[package]
name = "minebot"
version = "0.1.0"
authors = ["Joe Frikker <jfrikker@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4.5"
log = "0.4"
nbt = { path = "../nbt" }
packets = { path = "../packets" }
quick-error = "1.2"
stderrlog = "0.4"