[package]
name = "packets"
version = "0.1.0"
authors = ["Joe Frikker <jfrikker@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4.5"
json = "0.11"
nbt = { path = "../nbt" }
nbt-derive = { path = "../nbt-derive" }